name: Build AOSP for GT-P3100

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git-core gnupg flex bison build-essential zip curl \
          zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 \
          lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev \
          libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig

    - name: Initialize AOSP source
      run: |
        mkdir -p ~/android/aosp
        cd ~/android/aosp
        repo init -u https://android.googlesource.com/platform/manifest -b android-11.0.0_r46
        repo sync -c -j4 || repo sync -c -j1

    - name: Set up environment
      run: |
        cd ~/android/aosp
        source build/envsetup.sh
        lunch aosp_p3100-userdebug

    - name: Build ROM
      run: |
        cd ~/android/aosp
        make -j$(nproc)

    -     - name: Upload ROM artifact
      uses: actions/upload-artifact@v4
      with:
        name: aosp-gtp3100
        path: ~/android/aosp/out/target/product/p3100/*.zip

