name: Build AOSP for GT-P3100

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git-core gnupg flex bison build-essential zip curl \
          zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 \
          lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev \
          libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig python3

    - name: Install Repo Tool
      run: |
        sudo curl https://storage.googleapis.com/git-repo-downloads/repo > /usr/local/bin/repo
        sudo chmod a+x /usr/local/bin/repo

    - name: Initialize AOSP source (with fallback)
      run: |
        mkdir -p ~/android/aosp
        cd ~/android/aosp
        set +e
        repo init -u https://android.googlesource.com/platform/manifest -b android-11.0.0_r46
        if [ $? -ne 0 ]; then
          echo "Repo init failed, trying LineageOS manifest..."
          repo init -u https://github.com/LineageOS/android.git -b lineage-18.1
        fi
        set -e
        repo sync -c -j4 || repo sync -c -j1

    - name: Clone Device Tree & Kernel
      run: |
        cd ~/android/aosp
        git clone https://github.com/LineageOS/android_device_samsung_p3100 device/samsung/p3100
        git clone https://github.com/TheMuppets/proprietary_vendor_samsung vendor/samsung
        git clone https://github.com/LineageOS/android_kernel_samsung_omap4 kernel/samsung/omap4

    - name: Set up environment
      run: |
        cd ~/android/aosp
        source build/envsetup.sh
        lunch lineage_p3100-userdebug

    - name: Build ROM
      run: |
        cd ~/android/aosp
        make bacon -j$(nproc)

    - name: Upload ROM artifact
      uses: actions/upload-artifact@v4
      with:
        name: aosp-gtp3100
        path: ~/android/aosp/out/target/product/p3100/*.zip
