name: Build GT-P3100 ROM (FINAL ATTEMPT)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      ROM_BRANCH: cm-14.1
      DEVICE: p3100
      CCACHE_SIZE: 5G
      SRC: $HOME/android/lineage

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git-core gnupg flex bison build-essential zip curl \
        zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev \
        x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils \
        xsltproc unzip fontconfig python-is-python3 bc ccache repo openjdk-8-jdk-headless
        java -version

    - name: Configure git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Prepare Source Directory
      run: mkdir -p "$SRC"

    - name: Repo Init
      run: |
        cd "$SRC"
        repo init -u https://github.com/LineageOS/android.git -b "$ROM_BRANCH" || exit 1

    - name: Repo Sync
      run: |
        cd "$SRC"
        n=0
        until [ $n -ge 3 ]; do
          echo "Attempt $((n+1)) for repo sync..."
          repo sync -c --no-clone-bundle --no-tags -j4 && break
          n=$((n+1))
          sleep 30
        done
        if [ $n -ge 3 ]; then
          echo "Repo sync failed after 3 attempts."
          exit 1
        fi

    - name: Lunch Environment
      run: |
        cd "$SRC"
        export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
        export PATH=$JAVA_HOME/bin:$PATH
        export USE_CCACHE=1
        ccache -M $CCACHE_SIZE
        source build/envsetup.sh
        lunch lineage_${DEVICE}-userdebug

    - name: Build ROM
      run: |
        cd "$SRC"
        export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
        export PATH=$JAVA_HOME/bin:$PATH
        mka bacon -j$(nproc) || make bacon -j1

    - name: Upload Artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: gtp3100-rom
        path: |
          ${{ env.SRC }}/out/target/product/*/*.zip
          ${{ env.SRC }}/out/target/product/*/boot*.img
          ${{ env.SRC }}/out/target/product/*/recovery*.img
